@FMLab.Aspnet.URLShortener.Api_HostAddress = http://localhost:9000
@ApiKey = e6ae77d8-95b0-4627-b6b9-aa2a56b78474

POST {{FMLab.Aspnet.URLShortener.Api_HostAddress}}/api/v1/Url
Content-Type: application/json
X-Api-Key: {{ApiKey}}

{
  "target": "https://google.com",
  "temporaryRedirection": true
}

###

GET {{FMLab.Aspnet.URLShortener.Api_HostAddress}}/api/v1/RZWj
X-Api-Key: {{ApiKey}}

###

PATCH {{FMLab.Aspnet.URLShortener.Api_HostAddress}}/api/v1/Url/RZWj
Content-Type: application/json
X-Api-Key: {{ApiKey}}
{
  "Target": "https://duckduckgo.com"
}

###

DELETE {{FMLab.Aspnet.URLShortener.Api_HostAddress}}/api/v1/RZWj
X-Api-Key: {{ApiKey}}

###
GET {{FMLab.Aspnet.URLShortener.Api_HostAddress}}/api/health